### ISSUE TITLE
Errors Spammed when Aura Put on Character

### ISSUE THREAD

**Issue by jputman** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#14]
So, 

From time to time, and I am not sure what the trigger is but all of a sudden in the console will get spammed with errors around the aura function. If I turn off the aura, or remove it from the character the errors immediately stop. If I put it back on the character, I get a spam of errors immediately, with nothing else actually happening. 

I am attaching a few screen shots that indicate the issue, but as I said, it doesn't happen immediately or all the time either. [](url)

![Aura - Map](https://user-images.githubusercontent.com/9375319/121827708-03ba6600-cc8b-11eb-8c91-ff14f839a356.png)
![Aura - Character Sheet with Effect](https://user-images.githubusercontent.com/9375319/121827709-0452fc80-cc8b-11eb-9892-4431e2c67695.png)
![Aura - Console Messages](https://user-images.githubusercontent.com/9375319/121827710-0452fc80-cc8b-11eb-8222-1d51480553cb.png)

**Comment by bmos** [comment]
same issue as https://github.com/bmos/FG-Aura-Effect/issues/10
