### ISSUE TITLE
Error since last ruleset update

### ISSUE THREAD

**Issue by gravagehulk** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#20]
I confirmed that Aura Effects is causing this by creating a new Campaign with only Aura Effects and Better Combat Effects, then tested again with just Ongoing Save Effects. With either pair enabled and something like Pass without Trace or Spirit Guardians auras on a token, moving that token (or any tokens affected by the aura) results in getting spammed with this message:

"UtilityManager.isClientFGU - Deprecated - 2022-07-12 - Contact forge/extension author" 

The Aura itself still seems to work, it just fills up the chat log with that error for every square a token moves.

**Comment by bmos** [comment]
What version of Aura Effect and BCE is shown in chat when you load them up?

**Comment by gravagehulk** [comment]
Sorry. Just figured this out. I had an outdated version in the extensions folder.
