### ISSUE TITLE
Auras don't update when tokens are added

### ISSUE THREAD

**Issue by bmos** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#37]
If you create a CT entry and add an aura effect to it and then add the token to the map, it doesn't take effect until the token is moved.
https://www.fantasygrounds.com/forums/showthread.php?57417-5E-Aura-Effects&p=717488&viewfull=1#post717488

**Comment by rhagelstrom** [comment]
This is expected and working depending on what you have as descriptors. Not enough information so need more information or recommend close.

**Comment by rhagelstrom** [comment]
second thought maybe. I can take a look but I still feel like this user error

**Comment by bmos** [comment]
I used to tie into the token add function.
I think I removed it because it was redundant but with the new v3 system it probably isn't anymore.

**Comment by rhagelstrom** [comment]
It appears this is happening. It is also not removing applied auras if the source is deleted from the map. I'll look at it and put in a PR
