### ISSUE TITLE
Errors when moving a token which isn't in the combat tracker

### ISSUE THREAD

**Issue by SoxMax** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#4]
Encountered this last night, when I moved a token which didn't have a combat tracker node into range all non-gms were spammed with errors.

https://i.imgur.com/9Kw4NwF.png

**Comment by SoxMax** [comment]
I should have time to take a look at this tonight, I suspect its just an unexpected `nil` error.

**Comment by SoxMax** [comment]
Nevermind looks like @bmos already solved it with the refactor to `notifyPlayerMove(tokenMap)`

**Comment by bmos** [comment]
;D
