### ISSUE TITLE
Empty Effect Lines Left Over

### ISSUE THREAD

**Issue by jputman** [FG-Unofficial-Developers-Guild/FG-Aura-Effect#9]
As tokens move in and out of the Aura range it sometimes is leaving behind an empty effect line that has to be manually removed. See image for example.

![2021-05-19 21_06_16-Fantasy Grounds](https://user-images.githubusercontent.com/9375319/118904681-5dc44780-b8e8-11eb-8c7f-55e1cf187358.png)

**Comment by jputman** [comment]
I am not sure the exact root cause of this, as I can not actually easily replicate it, but I have seen it a few times. It only shows up if you expand a sheet in the CT as they are blank so if it is collapsed nothing appears to be out of the ordinary.

**Comment by bmos** [comment]
oh, interesting! thanks for the report.

**Comment by SoxMax** [comment]
I saw this in my game last night too. I think its related to unlocked token movement, I'll see if I can pin it down tonight.

**Comment by SoxMax** [comment]
Update on this.
I've had difficulty reproducing. I think it only pops up with more network latency than I can generate locally. I have a game coming up this week though that should have that and I'll see if bmos latest changes will have inadvertently fixed it. Otherwise I'll see if I can get a few of them to stick around for testing.

**Comment by jputman** [comment]
I have a game tomorrow as well, and will keep an eye on it.

**Comment by bmos** [comment]
I could also connect to your host SoxMax if you aren't able to do testing.

**Comment by bmos** [comment]
potential fix in progress in pull request #11

**Comment by bmos** [comment]
@jputman are you still seeing this issue as of [v1.2](https://github.com/bmos/FG-Aura-Effect/releases/tag/v1.2)?

**Comment by SoxMax** [comment]
Argh I saw this show up in my game again. Back to trying to reproduce reliably.

**Comment by bmos** [comment]
> Argh I saw this show up in my game again. Back to trying to reproduce reliably.

Are you using the silent effect option?

**Comment by SoxMax** [comment]
Ohh, that's really interesting with the DB listeners triggering off our own deletes. And yea I almost always use silent effects, else the chat window ends up overfilled. I actually think we could probably remove option and just make all AURA effects silent.

**Comment by bmos** [comment]
While I haven't had a game in FG for months so I can't say from personal experience, my preference is to leave the option as I would like those notices personally.

The remove handler, delete, re-add handler commit is to avoid potential errors which I sometimes see in the console upon closing the program. The error is something like "Object (DATABASENODE) deleted without cleaning up attached Lua object."

**Comment by bmos** [comment]
I believe this has been resolved
